package com.sloyardms.mediaservice.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Represents a parody associated with media content.
 * This entity is used to capture details of any derivative or parody-based elements of a media item.
 * Each parody is uniquely identified by a name.
 * <p>
 * Relationships:
 * - The {@code MediaParody} entity can be associated with media items, as evident in relationships defined in other entities like {@code Media}.
 * <p>
 * Primary Fields:
 * - {@code id}: The unique identifier for the parody, automatically generated by the persistence provider.
 * - {@code name}: The unique name of the parody.
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Entity
@Table(name = "parodies")
public class MediaParody extends BaseAuditableEntity{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "name", unique = true)
    private String name;

}
