package com.sloyardms.mediaservice.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Represents a tag that can be associated with media to classify or describe it.
 * Each tag has a unique name and serves as a categorization mechanism for media entities.
 * <p>
 * The class extends {@code BaseAuditableEntity}, inheriting audit-related fields and
 * behaviors for tracking creation and modification timestamps.
 * <p>
 * Relationships:
 * - Used in a many-to-many relationship with {@code Media} entities to associate one or more tags with a media item.
 * <p>
 * Primary Fields:
 * - {@code id}: The unique identifier for the tag, automatically generated by the persistence provider.
 * - {@code name}: The unique name of the tag used for categorization.
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Entity
@Table(name = "tags")
public class MediaTag extends BaseAuditableEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "name", unique = true)
    private String name;

}
