package com.sloyardms.mediaservice.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Represents a character that may be associated with media entities.
 * This entity contains a unique identifier (ID) and a character name, which must be unique.
 * <p>
 * The class extends {@code BaseAuditableEntity}, inheriting audit-related fields and
 * behaviors for tracking creation and modification timestamps.
 * <p>
 * Relationships:
 * - This entity is designed to be associated with media through a many-to-many relationship,
 *   as indicated in other entities like {@code Media}.
 * <p>
 * Primary Fields:
 * - {@code id}: A unique identifier for the character, automatically generated by the persistence provider.
 * - {@code name}: The unique name of the character.
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Entity
@Table(name = "characters")
public class MediaCharacter extends BaseAuditableEntity{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "name", unique = true)
    private String name;

}
