package com.sloyardms.mediaservice.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Represents an author who creates or contributes to media content.
 * This entity contains basic information about an author, including a unique identifier (ID)
 * and a name that must be unique.
 * <p>
 * The class extends {@code BaseAuditableEntity}, inheriting audit-related fields and
 * behaviors for tracking creation and modification timestamps.
 * <p>
 * Relationships:
 * - This entity is designed to be associated with media through a many-to-many relationship,
 *   as indicated in other entities like {@code Media}.
 * <p>
 * Primary Fields:
 * - {@code id}: The unique identifier for the author, automatically generated by the persistence provider.
 * - {@code name}: The name of the author, which must be unique in the database.
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Entity
@Table(name = "authors")
public class MediaAuthor extends BaseAuditableEntity{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "name", unique = true)
    private String name;

}
