-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.artists
(
    created_at timestamp with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp with time zone NOT NULL,
    created_by character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT artists_pkey PRIMARY KEY (id),
    CONSTRAINT artists_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.authors
(
    created_at timestamp with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp with time zone NOT NULL,
    created_by character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT authors_pkey PRIMARY KEY (id),
    CONSTRAINT authors_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.characters
(
    created_at timestamp with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp with time zone NOT NULL,
    created_by character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT characters_pkey PRIMARY KEY (id),
    CONSTRAINT characters_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.languages
(
    created_at timestamp with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp with time zone NOT NULL,
    created_by character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT languages_pkey PRIMARY KEY (id),
    CONSTRAINT languages_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.media
(
    release_year integer,
    created_at timestamp with time zone NOT NULL,
    media_language_id bigint,
    media_status_id bigint,
    media_type_id bigint,
    parody_id bigint,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    created_by character varying(255) COLLATE pg_catalog."default",
    main_title character varying(255) COLLATE pg_catalog."default",
    source_url character varying(255) COLLATE pg_catalog."default",
    summary character varying(255) COLLATE pg_catalog."default",
    thumbnail_url character varying(255) COLLATE pg_catalog."default",
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT media_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.media_alternate_titles
(
    created_at timestamp with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp with time zone NOT NULL,
    media_id uuid,
    created_by character varying(255) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT media_alternate_titles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.media_artists
(
    artist_id bigint NOT NULL,
    media_id uuid NOT NULL,
    CONSTRAINT media_artists_pkey PRIMARY KEY (artist_id, media_id)
);

CREATE TABLE IF NOT EXISTS public.media_authors
(
    author_id bigint NOT NULL,
    media_id uuid NOT NULL,
    CONSTRAINT media_authors_pkey PRIMARY KEY (author_id, media_id)
);

CREATE TABLE IF NOT EXISTS public.media_characters
(
    character_id bigint NOT NULL,
    media_id uuid NOT NULL,
    CONSTRAINT media_characters_pkey PRIMARY KEY (character_id, media_id)
);

CREATE TABLE IF NOT EXISTS public.media_status
(
    created_at timestamp with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp with time zone NOT NULL,
    created_by character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT media_status_pkey PRIMARY KEY (id),
    CONSTRAINT media_status_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.media_tags
(
    tag_id bigint NOT NULL,
    media_id uuid NOT NULL,
    CONSTRAINT media_tags_pkey PRIMARY KEY (tag_id, media_id)
);

CREATE TABLE IF NOT EXISTS public.media_types
(
    created_at timestamp with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp with time zone NOT NULL,
    created_by character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT media_types_pkey PRIMARY KEY (id),
    CONSTRAINT media_types_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.parodies
(
    created_at timestamp with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp with time zone NOT NULL,
    created_by character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT parodies_pkey PRIMARY KEY (id),
    CONSTRAINT parodies_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.tags
(
    created_at timestamp with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp with time zone NOT NULL,
    created_by character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tags_pkey PRIMARY KEY (id),
    CONSTRAINT tags_name_key UNIQUE (name)
);

ALTER TABLE IF EXISTS public.media
    ADD CONSTRAINT fk2qqcj8qbxhywuhexjeovfowtq FOREIGN KEY (media_status_id)
    REFERENCES public.media_status (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_media_status
    ON public.media(media_status_id);


ALTER TABLE IF EXISTS public.media
    ADD CONSTRAINT fk9s7n2vno5i5bdntvstpbcdm6h FOREIGN KEY (parody_id)
    REFERENCES public.parodies (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.media
    ADD CONSTRAINT fkn1n2mbq80xg16pt8c5436qv35 FOREIGN KEY (media_type_id)
    REFERENCES public.media_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_media_type_id
    ON public.media(media_type_id);


ALTER TABLE IF EXISTS public.media
    ADD CONSTRAINT fkssebl3ysosaglf7vd6wv118cp FOREIGN KEY (media_language_id)
    REFERENCES public.languages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_media_language_id
    ON public.media(media_language_id);


ALTER TABLE IF EXISTS public.media_alternate_titles
    ADD CONSTRAINT fk1rtfhkg22me8x6o0bvj9c602x FOREIGN KEY (media_id)
    REFERENCES public.media (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.media_artists
    ADD CONSTRAINT fkb1xggdrljje6i3omvwx4uygkh FOREIGN KEY (media_id)
    REFERENCES public.media (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.media_artists
    ADD CONSTRAINT fkq347clv3hol62r3n1iofyape9 FOREIGN KEY (artist_id)
    REFERENCES public.artists (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.media_authors
    ADD CONSTRAINT fk9dfaauwoujlvucytgx8ca2paf FOREIGN KEY (media_id)
    REFERENCES public.media (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.media_authors
    ADD CONSTRAINT fkl6ya7x2ad4iwcnl79kv6k8cke FOREIGN KEY (author_id)
    REFERENCES public.authors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.media_characters
    ADD CONSTRAINT fkikhca4xa48l96duvu8i3wwnlu FOREIGN KEY (character_id)
    REFERENCES public.characters (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.media_characters
    ADD CONSTRAINT fklf4ys8t3i3no4snto8ess5ina FOREIGN KEY (media_id)
    REFERENCES public.media (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.media_tags
    ADD CONSTRAINT fk88c8wcoplis4o99y53ccn21gt FOREIGN KEY (media_id)
    REFERENCES public.media (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.media_tags
    ADD CONSTRAINT fkfginody5nx4qltqey6c6s16lt FOREIGN KEY (tag_id)
    REFERENCES public.tags (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;